#!/usr/bin/env bash
export AWS_CONFIG_FILE="/root/.aws.cfg"

if [ "$1" == "-q" ]; then
  output="/dev/null"
else
  output="/dev/stdout"
fi

for file in /srv/backups/production_obsqure-*; do
  encrypted_file=`$(dirname $0)/encrypt $file`
  `dirname $0`/to_s3 MySQL ${encrypted_file}
done
