#!/usr/bin/env bash
export AWS_CONFIG_FILE="/root/.aws.cfg"
datestamp=$(date +"%Y-%m-%dT%H-%M-%S")
backup_file="/srv/backups/git-${datestamp}.tar.bz2"

if [ "$1" == "-q" ]; then
  output="/dev/null"
else
  output="/dev/stdout"
fi

pushd /srv > /dev/null
tar jcvf $backup_file git/ &> $output
popd > /dev/null

for file in /srv/backups/git-*.tar.bz2; do
  encrypted_file=`$(dirname $0)/encrypt $file`
  `dirname $0`/to_s3 Git ${encrypted_file}
done
