#!/usr/bin/env bash
datestamp=$(date +"%Y-%m-%dT%H-%M-%S")
backup_file="/srv/backups/system_files-${datestamp}.tar.bz2"

if [ "$1" == "-q" ]; then
  output="/dev/null"
else
  output="/dev/stdout"
fi

tar jcf $backup_file \
  /etc/apt/*              \
  /etc/cron*              \
  /etc/group              \
  /etc/hosts              \
  /etc/iptables/*         \
  /etc/logrotate.d/*      \
  /etc/munin/*            \
  /etc/mysql/*            \
  /etc/passwd             \
  /etc/sudoers            \
  /var/cache/munin/www/*  \
  /var/spool/mail/*       \
  &> /dev/null

for file in /srv/backups/system_files-*.tar.bz2; do
  encrypted_file=`$(dirname $0)/encrypt $file`
  `dirname $0`/to_s3 Alpha ${encrypted_file}
done
