#!/usr/bin/env bash

function new_file_for() {
  # get last modification time
  log_type=$2
  original_file=`basename $1 | sed s/\.log.*//`
  tmp_file="${original_file}-$(date --date="`stat --format=%y $1`" +"%Y-%m-%dT%H-%M-%S").log"
  new_file="/srv/backups/$log_type/$tmp_file"

  if [ ! -d `dirname $new_file` ]; then
    mkdir -p `dirname $new_file`
  fi

  echo $new_file
}

for type in NGINX MySQL Obsqure Postfix; do
  case $type in
    "NGINX")
      dir="/var/log/nginx/*.log.[0-9]"
    ;;
    "MySQL")
      dir="/var/log/mysql/*.log.[0-9]"
    ;;
    "Obsqure")
      dir="/srv/www/obsqure/shared/logs/*.log.[0-9]"
    ;;
    "Postfix")
      dir="/var/log/mail*.[0-9]"
    ;;
    *)
      dir=""
    ;;
  esac

  # encrypt the log
  for file in $dir; do
    if [ -f $file ]; then
      LOG=`new_file_for $file $type`
      mv $file $LOG
      `dirname $0`/encrypt --compress $LOG
    fi
  done 

  # upload encrypted log to s3.
  for backup in /srv/backups/$type/*.log.gpg; do
    if [ -f $backup ]; then
      `dirname $0`/to_s3 "Logs/$type" $backup
    fi
  done

done
