#!/usr/bin/env bash
if [ "$1" == "--compress" ]; then
  compress="--compress-level 6"
  shift
else
  compress="--compress-level 0"
fi

if [ $# -lt 1 ]; then
  echo "gotta give me a file to encrypt"
  exit 1
fi

# don't encrypt an encrypted file.
if echo "$1" | grep "\.gpg$"; then
  echo $1
  exit 0
fi

gpg -e --compress-level 0 -R "Jon Higgs" $1 &> /dev/null
rm -f $1
echo "${1}.gpg"
