#!/bin/bash
dir="/srv/www/obsqure/current"
unicorn_bin="/usr/local/bin/unicorn_rails"
unicorn_config="${dir}/config/unicorn.rb"
unicorn_pid="${dir}/tmp/pids/unicorn.pid"

if [ -z "${RAILS_ENV}" ]; then RAILS_ENV="development"; fi

case $1 in
  "start")
    echo "starting unicorn"
    sudo start unicorn-obsqure
  ;;
  "stop")
    echo "stopping unicorn"
    sudo stop unicorn-obsqure
  ;;
  "graceful-stop")
    echo "gracefully stopping unicorn"
    if [ -f $unicorn_pid ]; then kill -s QUIT `cat ${unicorn_pid}`; fi
  ;;
  "reload")
    echo "reloading unicorn config"
    if [ -f $unicorn_pid ]; then kill -s USR2 `cat #{unicorn_pid}`; fi
  ;;
  "restart")
    echo "restarting unicorn"
    sudo restart unicorn-obsqure
  ;;
  *)
    echo "options are start|stop|graceful-stop|reload|restart"
  ;;
esac
